---
- name: Ensure directory exists for local self-signed TLS certs.
  file:
    path: /etc/letsencrypt/live/{{ fqdn }}
    state: directory

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: /etc/letsencrypt/live/{{ fqdn }}/privkey.pem

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: /etc/ssl/private/{{ fqdn }}.csr
    privatekey_path: /etc/letsencrypt/live/{{ fqdn }}/privkey.pem
    common_name: "{{ fqdn }}"

- name: Generate a Self Signed OpenSSL certificate.
  openssl_certificate:
    path: /etc/letsencrypt/live/{{ fqdn }}/fullchain.pem
    privatekey_path: /etc/letsencrypt/live/{{ fqdn }}/privkey.pem
    csr_path: /etc/ssl/private/{{ fqdn }}.csr
    provider: selfsigned