---
- import_tasks: nodeapp-install.yml
  tags: ["nodeapp", "nodeapp:install", "install"]

- import_tasks: nodeapp-config.yml
  tags: ["nodeapp", "nodeapp:config", "config"]

- import_tasks: nodeapp-service.yml
  tags: ["nodeapp", "nodeapp:service", "service"]

