---

- name: Install a list of extra packages
  apt:
    pkg: "{{ extra_packages }}"
    state: present

#- name: Ensure python OpenSSL dependencies are installed.
#  pip:
#    name: pyOpenSSL
#    state: present

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Download mozilla recommended SSL DH params
  get_url:
    url: https://ssl-config.mozilla.org/ffdhe2048.txt
    dest: "{{ ssl_dhparam_file }}"
    group: root
    owner: root
    mode: 0644
  notify: Test nginx and restart
